[package]
name = "ventil"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.28"
sea-orm = { version = "1.1.7", features = [ "sqlx-sqlite", "runtime-async-std-native-tls", "macros" ] }
sea-orm-migration = "1.1"
async-std = "1.13"
